import { createI18n, defineStrings } from '@genoffice/i18n'

/**
 * Strings for the shared AI provider dialog. They live with the component
 * rather than in each app's dictionary because all five apps mount the same
 * dialog — one shard means one translation pass instead of five.
 */
export const aiSettingsStrings = defineStrings({
  zh: {
    title: 'AI 模型',
    provider: '提供方',
    model: '模型',
    modelHint: '可从列表中选择，也可直接填写提供方支持的任意模型 ID。',
    apiKey: 'API Key',
    apiKeyKeep: '已保存密钥；留空即保持不变。',
    removeKey: '删除密钥',
    baseUrl: 'Base URL',
    baseUrlHint: '兼容 OpenAI 的接口地址，例如 https://example.com/v1',
    gensparkHosted: '模型调用经由 Genspark 服务端转发，本机不保存密钥。',
    signIn: '登录 Genspark',
    signedInAs: '已登录：{email}',
    notSignedIn: '尚未登录',
    storageNote:
      '密钥仅保存在本机，在系统提供密钥链时加密存储，且只会随请求发送给你所选择的提供方。',
    save: '保存',
    cancel: '取消',
    test: '测试',
    testing: '测试中…',
    testOk: '密钥可用',
    refresh: '刷新模型列表',
    refreshing: '刷新中…',
    noModels: '该提供方未返回任何模型',
    noMatches: '没有匹配的模型',
    cliInstalled: '已安装',
    cliMissing: '未检测到 {name}。请先安装并确认可在终端运行。',
    cliNote: '改用本机已登录的 {name}，无需 API Key。',
    switchModel: '切换 AI 模型',
    cliDefaultModel: 'CLI 默认模型',
    moreModels: 'AI 模型设置…',
    presets: '预设',
    savePreset: '存为预设',
    presetName: '预设名称',
    deletePreset: '删除预设',
    errApiKey: '请填写 API Key',
    errModel: '请填写模型 ID',
    errBaseUrl: '自定义提供方需要填写 Base URL',
  },
  en: {
    title: 'AI model',
    provider: 'Provider',
    model: 'Model',
    modelHint: 'Pick one from the list, or type any model id the provider accepts.',
    apiKey: 'API key',
    apiKeyKeep: 'A key is saved. Leave this empty to keep it.',
    removeKey: 'Remove key',
    baseUrl: 'Base URL',
    baseUrlHint: 'OpenAI-compatible endpoint, for example https://example.com/v1',
    gensparkHosted: 'Model calls are routed through Genspark. No key is stored on this device.',
    signIn: 'Sign in to Genspark',
    signedInAs: 'Signed in as {email}',
    notSignedIn: 'Not signed in',
    storageNote:
      'Keys are stored on this device, encrypted with the system keychain where one is available, and are only ever sent to the provider you chose.',
    save: 'Save',
    cancel: 'Cancel',
    test: 'Test',
    testing: 'Testing…',
    testOk: 'Key works',
    refresh: 'Refresh model list',
    refreshing: 'Refreshing…',
    noModels: 'The provider returned no models',
    noMatches: 'No matching model',
    cliInstalled: 'Installed',
    cliMissing: '{name} was not found. Install it and make sure it runs in a terminal.',
    cliNote: 'Uses the {name} you already have installed and signed in. No API key needed.',
    switchModel: 'Switch AI model',
    cliDefaultModel: 'CLI default',
    moreModels: 'AI model settings…',
    presets: 'Presets',
    savePreset: 'Save as preset',
    presetName: 'Preset name',
    deletePreset: 'Delete preset',
    errApiKey: 'Enter an API key',
    errModel: 'Enter a model id',
    errBaseUrl: 'A custom provider needs a base URL',
  },
  ja: {
    title: 'AI モデル',
    provider: 'プロバイダー',
    model: 'モデル',
    modelHint: '一覧から選ぶか、プロバイダーが受け付けるモデル ID を直接入力できます。',
    apiKey: 'API キー',
    apiKeyKeep: 'キーは保存済みです。空のままにすると変更されません。',
    removeKey: 'キーを削除',
    baseUrl: 'ベース URL',
    baseUrlHint: 'OpenAI 互換のエンドポイント。例: https://example.com/v1',
    gensparkHosted: 'モデル呼び出しは Genspark 経由で行われます。この端末にキーは保存されません。',
    signIn: 'Genspark にログイン',
    signedInAs: 'ログイン中: {email}',
    notSignedIn: '未ログイン',
    storageNote:
      'キーはこの端末にのみ保存され、システムのキーチェーンが利用できる場合は暗号化されます。送信先は選択したプロバイダーだけです。',
    save: '保存',
    cancel: 'キャンセル',
    test: 'テスト',
    testing: 'テスト中…',
    testOk: 'キーは有効です',
    refresh: 'モデル一覧を更新',
    refreshing: '更新中…',
    noModels: 'プロバイダーがモデルを返しませんでした',
    noMatches: '一致するモデルはありません',
    cliInstalled: 'インストール済み',
    cliMissing:
      '{name} が見つかりません。インストールし、ターミナルで動作することを確認してください。',
    cliNote: 'インストール済みでログイン済みの {name} を使います。API キーは不要です。',
    switchModel: 'AI モデルを切り替え',
    cliDefaultModel: 'CLI の既定モデル',
    moreModels: 'AI モデル設定…',
    presets: 'プリセット',
    savePreset: 'プリセットとして保存',
    presetName: 'プリセット名',
    deletePreset: 'プリセットを削除',
    errApiKey: 'API キーを入力してください',
    errModel: 'モデル ID を入力してください',
    errBaseUrl: 'カスタムプロバイダーにはベース URL が必要です',
  },
  ko: {
    title: 'AI 모델',
    provider: '제공자',
    model: '모델',
    modelHint: '목록에서 고르거나, 제공자가 지원하는 모델 ID를 직접 입력하세요.',
    apiKey: 'API 키',
    apiKeyKeep: '키가 저장되어 있습니다. 비워 두면 그대로 유지됩니다.',
    removeKey: '키 삭제',
    baseUrl: '기본 URL',
    baseUrlHint: 'OpenAI 호환 엔드포인트. 예: https://example.com/v1',
    gensparkHosted: '모델 호출은 Genspark를 거칩니다. 이 기기에는 키가 저장되지 않습니다.',
    signIn: 'Genspark 로그인',
    signedInAs: '로그인됨: {email}',
    notSignedIn: '로그인하지 않음',
    storageNote:
      '키는 이 기기에만 저장되며 시스템 키체인을 사용할 수 있으면 암호화됩니다. 선택한 제공자에게만 전송됩니다.',
    save: '저장',
    cancel: '취소',
    test: '테스트',
    testing: '테스트 중…',
    testOk: '키가 작동합니다',
    refresh: '모델 목록 새로고침',
    refreshing: '새로고침 중…',
    noModels: '제공자가 모델을 반환하지 않았습니다',
    noMatches: '일치하는 모델 없음',
    cliInstalled: '설치됨',
    cliMissing: '{name}을(를) 찾을 수 없습니다. 설치 후 터미널에서 실행되는지 확인하세요.',
    cliNote: '이미 설치하고 로그인한 {name}을(를) 사용합니다. API 키가 필요 없습니다.',
    switchModel: 'AI 모델 전환',
    cliDefaultModel: 'CLI 기본 모델',
    moreModels: 'AI 모델 설정…',
    presets: '프리셋',
    savePreset: '프리셋으로 저장',
    presetName: '프리셋 이름',
    deletePreset: '프리셋 삭제',
    errApiKey: 'API 키를 입력하세요',
    errModel: '모델 ID를 입력하세요',
    errBaseUrl: '사용자 지정 제공자는 기본 URL이 필요합니다',
  },
  fr: {
    title: 'Modèle IA',
    provider: 'Fournisseur',
    model: 'Modèle',
    modelHint:
      'Choisissez dans la liste ou saisissez tout identifiant de modèle accepté par le fournisseur.',
    apiKey: 'Clé API',
    apiKeyKeep: 'Une clé est enregistrée. Laissez vide pour la conserver.',
    removeKey: 'Supprimer la clé',
    baseUrl: 'URL de base',
    baseUrlHint: 'Point de terminaison compatible OpenAI, par exemple https://example.com/v1',
    gensparkHosted:
      'Les appels au modèle passent par Genspark. Aucune clé n’est stockée sur cet appareil.',
    signIn: 'Se connecter à Genspark',
    signedInAs: 'Connecté en tant que {email}',
    notSignedIn: 'Non connecté',
    storageNote:
      'Les clés sont stockées sur cet appareil, chiffrées via le trousseau système lorsqu’il est disponible, et ne sont envoyées qu’au fournisseur choisi.',
    save: 'Enregistrer',
    cancel: 'Annuler',
    test: 'Tester',
    testing: 'Test en cours…',
    testOk: 'La clé fonctionne',
    refresh: 'Actualiser la liste des modèles',
    refreshing: 'Actualisation…',
    noModels: 'Le fournisseur n’a renvoyé aucun modèle',
    noMatches: 'Aucun modèle correspondant',
    cliInstalled: 'Installé',
    cliMissing:
      '{name} est introuvable. Installez-le et vérifiez qu’il fonctionne dans un terminal.',
    cliNote: 'Utilise le {name} déjà installé et connecté. Aucune clé API nécessaire.',
    switchModel: 'Changer de modèle IA',
    cliDefaultModel: 'Modèle par défaut du CLI',
    moreModels: 'Paramètres du modèle IA…',
    presets: 'Préréglages',
    savePreset: 'Enregistrer comme préréglage',
    presetName: 'Nom du préréglage',
    deletePreset: 'Supprimer le préréglage',
    errApiKey: 'Saisissez une clé API',
    errModel: 'Saisissez un identifiant de modèle',
    errBaseUrl: 'Un fournisseur personnalisé nécessite une URL de base',
  },
  de: {
    title: 'KI-Modell',
    provider: 'Anbieter',
    model: 'Modell',
    modelHint:
      'Aus der Liste wählen oder eine beliebige vom Anbieter unterstützte Modell-ID eingeben.',
    apiKey: 'API-Schlüssel',
    apiKeyKeep: 'Ein Schlüssel ist gespeichert. Leer lassen, um ihn beizubehalten.',
    removeKey: 'Schlüssel entfernen',
    baseUrl: 'Basis-URL',
    baseUrlHint: 'OpenAI-kompatibler Endpunkt, zum Beispiel https://example.com/v1',
    gensparkHosted:
      'Modellaufrufe laufen über Genspark. Auf diesem Gerät wird kein Schlüssel gespeichert.',
    signIn: 'Bei Genspark anmelden',
    signedInAs: 'Angemeldet als {email}',
    notSignedIn: 'Nicht angemeldet',
    storageNote:
      'Schlüssel werden auf diesem Gerät gespeichert, sofern verfügbar mit dem Systemschlüsselbund verschlüsselt, und nur an den gewählten Anbieter gesendet.',
    save: 'Speichern',
    cancel: 'Abbrechen',
    test: 'Testen',
    testing: 'Wird getestet…',
    testOk: 'Schlüssel funktioniert',
    refresh: 'Modellliste aktualisieren',
    refreshing: 'Wird aktualisiert…',
    noModels: 'Der Anbieter hat keine Modelle zurückgegeben',
    noMatches: 'Kein passendes Modell',
    cliInstalled: 'Installiert',
    cliMissing:
      '{name} wurde nicht gefunden. Installieren Sie es und prüfen Sie, ob es im Terminal läuft.',
    cliNote: 'Nutzt das bereits installierte und angemeldete {name}. Kein API-Schlüssel nötig.',
    switchModel: 'KI-Modell wechseln',
    cliDefaultModel: 'CLI-Standardmodell',
    moreModels: 'KI-Modelleinstellungen…',
    presets: 'Voreinstellungen',
    savePreset: 'Als Voreinstellung speichern',
    presetName: 'Name der Voreinstellung',
    deletePreset: 'Voreinstellung löschen',
    errApiKey: 'API-Schlüssel eingeben',
    errModel: 'Modell-ID eingeben',
    errBaseUrl: 'Ein eigener Anbieter braucht eine Basis-URL',
  },
  es: {
    title: 'Modelo de IA',
    provider: 'Proveedor',
    model: 'Modelo',
    modelHint:
      'Elige uno de la lista o escribe cualquier identificador de modelo que acepte el proveedor.',
    apiKey: 'Clave de API',
    apiKeyKeep: 'Hay una clave guardada. Déjalo vacío para mantenerla.',
    removeKey: 'Eliminar clave',
    baseUrl: 'URL base',
    baseUrlHint: 'Endpoint compatible con OpenAI, por ejemplo https://example.com/v1',
    gensparkHosted:
      'Las llamadas al modelo pasan por Genspark. No se guarda ninguna clave en este dispositivo.',
    signIn: 'Iniciar sesión en Genspark',
    signedInAs: 'Sesión iniciada como {email}',
    notSignedIn: 'Sin iniciar sesión',
    storageNote:
      'Las claves se guardan en este dispositivo, cifradas con el llavero del sistema cuando está disponible, y solo se envían al proveedor que elijas.',
    save: 'Guardar',
    cancel: 'Cancelar',
    test: 'Probar',
    testing: 'Probando…',
    testOk: 'La clave funciona',
    refresh: 'Actualizar lista de modelos',
    refreshing: 'Actualizando…',
    noModels: 'El proveedor no devolvió ningún modelo',
    noMatches: 'Ningún modelo coincide',
    cliInstalled: 'Instalado',
    cliMissing: 'No se encontró {name}. Instálalo y comprueba que funciona en una terminal.',
    cliNote:
      'Usa el {name} que ya tienes instalado y con sesión iniciada. No necesita clave de API.',
    switchModel: 'Cambiar de modelo de IA',
    cliDefaultModel: 'Modelo predeterminado de la CLI',
    moreModels: 'Configuración del modelo de IA…',
    presets: 'Ajustes guardados',
    savePreset: 'Guardar como ajuste',
    presetName: 'Nombre del ajuste',
    deletePreset: 'Eliminar ajuste',
    errApiKey: 'Introduce una clave de API',
    errModel: 'Introduce un identificador de modelo',
    errBaseUrl: 'Un proveedor personalizado necesita una URL base',
  },
  th: {
    title: 'โมเดล AI',
    provider: 'ผู้ให้บริการ',
    model: 'โมเดล',
    modelHint: 'เลือกจากรายการ หรือพิมพ์รหัสโมเดลใดก็ได้ที่ผู้ให้บริการรองรับ',
    apiKey: 'คีย์ API',
    apiKeyKeep: 'มีคีย์บันทึกไว้แล้ว เว้นว่างไว้เพื่อคงคีย์เดิม',
    removeKey: 'ลบคีย์',
    baseUrl: 'Base URL',
    baseUrlHint: 'ปลายทางที่รองรับ OpenAI เช่น https://example.com/v1',
    gensparkHosted: 'การเรียกโมเดลผ่าน Genspark ไม่มีการเก็บคีย์บนเครื่องนี้',
    signIn: 'เข้าสู่ระบบ Genspark',
    signedInAs: 'เข้าสู่ระบบในชื่อ {email}',
    notSignedIn: 'ยังไม่ได้เข้าสู่ระบบ',
    storageNote:
      'คีย์จะถูกเก็บไว้บนเครื่องนี้ เข้ารหัสด้วยพวงกุญแจของระบบเมื่อใช้งานได้ และส่งไปยังผู้ให้บริการที่คุณเลือกเท่านั้น',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    test: 'ทดสอบ',
    testing: 'กำลังทดสอบ…',
    testOk: 'คีย์ใช้งานได้',
    refresh: 'รีเฟรชรายการโมเดล',
    refreshing: 'กำลังรีเฟรช…',
    noModels: 'ผู้ให้บริการไม่ได้ส่งรายการโมเดลกลับมา',
    noMatches: 'ไม่พบโมเดลที่ตรงกัน',
    cliInstalled: 'ติดตั้งแล้ว',
    cliMissing: 'ไม่พบ {name} กรุณาติดตั้งและตรวจสอบว่าใช้งานได้ในเทอร์มินัล',
    cliNote: 'ใช้ {name} ที่ติดตั้งและเข้าสู่ระบบไว้แล้ว ไม่ต้องใช้คีย์ API',
    switchModel: 'สลับโมเดล AI',
    cliDefaultModel: 'โมเดลเริ่มต้นของ CLI',
    moreModels: 'ตั้งค่าโมเดล AI…',
    presets: 'พรีเซ็ต',
    savePreset: 'บันทึกเป็นพรีเซ็ต',
    presetName: 'ชื่อพรีเซ็ต',
    deletePreset: 'ลบพรีเซ็ต',
    errApiKey: 'กรุณากรอกคีย์ API',
    errModel: 'กรุณากรอกรหัสโมเดล',
    errBaseUrl: 'ผู้ให้บริการแบบกำหนดเองต้องระบุ Base URL',
  },
  id: {
    title: 'Model AI',
    provider: 'Penyedia',
    model: 'Model',
    modelHint: 'Pilih dari daftar, atau ketik id model apa pun yang diterima penyedia.',
    apiKey: 'Kunci API',
    apiKeyKeep: 'Sebuah kunci tersimpan. Biarkan kosong untuk mempertahankannya.',
    removeKey: 'Hapus kunci',
    baseUrl: 'Base URL',
    baseUrlHint: 'Endpoint yang kompatibel dengan OpenAI, misalnya https://example.com/v1',
    gensparkHosted:
      'Panggilan model dirutekan melalui Genspark. Tidak ada kunci yang disimpan di perangkat ini.',
    signIn: 'Masuk ke Genspark',
    signedInAs: 'Masuk sebagai {email}',
    notSignedIn: 'Belum masuk',
    storageNote:
      'Kunci disimpan di perangkat ini, dienkripsi dengan keychain sistem bila tersedia, dan hanya dikirim ke penyedia yang Anda pilih.',
    save: 'Simpan',
    cancel: 'Batal',
    test: 'Uji',
    testing: 'Menguji…',
    testOk: 'Kunci berfungsi',
    refresh: 'Segarkan daftar model',
    refreshing: 'Menyegarkan…',
    noModels: 'Penyedia tidak mengembalikan model',
    noMatches: 'Tidak ada model yang cocok',
    cliInstalled: 'Terpasang',
    cliMissing: '{name} tidak ditemukan. Pasang dan pastikan dapat dijalankan di terminal.',
    cliNote: 'Memakai {name} yang sudah terpasang dan masuk. Tidak perlu kunci API.',
    switchModel: 'Ganti model AI',
    cliDefaultModel: 'Model bawaan CLI',
    moreModels: 'Pengaturan model AI…',
    presets: 'Prasetel',
    savePreset: 'Simpan sebagai prasetel',
    presetName: 'Nama prasetel',
    deletePreset: 'Hapus prasetel',
    errApiKey: 'Masukkan kunci API',
    errModel: 'Masukkan id model',
    errBaseUrl: 'Penyedia kustom memerlukan base URL',
  },
  ru: {
    title: 'Модель ИИ',
    provider: 'Провайдер',
    model: 'Модель',
    modelHint:
      'Выберите из списка или введите любой идентификатор модели, который принимает провайдер.',
    apiKey: 'API-ключ',
    apiKeyKeep: 'Ключ сохранён. Оставьте поле пустым, чтобы сохранить его.',
    removeKey: 'Удалить ключ',
    baseUrl: 'Базовый URL',
    baseUrlHint: 'Совместимая с OpenAI конечная точка, например https://example.com/v1',
    gensparkHosted: 'Запросы к модели идут через Genspark. Ключ на этом устройстве не хранится.',
    signIn: 'Войти в Genspark',
    signedInAs: 'Вы вошли как {email}',
    notSignedIn: 'Вход не выполнен',
    storageNote:
      'Ключи хранятся на этом устройстве, шифруются системным хранилищем ключей, если оно доступно, и отправляются только выбранному провайдеру.',
    save: 'Сохранить',
    cancel: 'Отмена',
    test: 'Проверить',
    testing: 'Проверка…',
    testOk: 'Ключ работает',
    refresh: 'Обновить список моделей',
    refreshing: 'Обновление…',
    noModels: 'Провайдер не вернул ни одной модели',
    noMatches: 'Нет подходящей модели',
    cliInstalled: 'Установлено',
    cliMissing: '{name} не найден. Установите его и убедитесь, что он запускается в терминале.',
    cliNote: 'Использует уже установленный {name} с выполненным входом. API-ключ не нужен.',
    switchModel: 'Сменить модель ИИ',
    cliDefaultModel: 'Модель CLI по умолчанию',
    moreModels: 'Настройки модели ИИ…',
    presets: 'Пресеты',
    savePreset: 'Сохранить как пресет',
    presetName: 'Название пресета',
    deletePreset: 'Удалить пресет',
    errApiKey: 'Введите API-ключ',
    errModel: 'Введите идентификатор модели',
    errBaseUrl: 'Для своего провайдера нужен базовый URL',
  },
  ar: {
    title: 'نموذج الذكاء الاصطناعي',
    provider: 'المزوّد',
    model: 'النموذج',
    modelHint: 'اختر من القائمة أو اكتب أي معرّف نموذج يقبله المزوّد.',
    apiKey: 'مفتاح API',
    apiKeyKeep: 'هناك مفتاح محفوظ. اتركه فارغًا للإبقاء عليه.',
    removeKey: 'حذف المفتاح',
    baseUrl: 'عنوان URL الأساسي',
    baseUrlHint: 'نقطة نهاية متوافقة مع OpenAI، مثل https://example.com/v1',
    gensparkHosted: 'تمرّ طلبات النموذج عبر Genspark. لا يُحفظ أي مفتاح على هذا الجهاز.',
    signIn: 'تسجيل الدخول إلى Genspark',
    signedInAs: 'مسجّل الدخول باسم {email}',
    notSignedIn: 'غير مسجّل الدخول',
    storageNote:
      'تُحفظ المفاتيح على هذا الجهاز، ومشفّرة بسلسلة مفاتيح النظام عند توفّرها، ولا تُرسل إلا إلى المزوّد الذي اخترته.',
    save: 'حفظ',
    cancel: 'إلغاء',
    test: 'اختبار',
    testing: 'جارٍ الاختبار…',
    testOk: 'المفتاح يعمل',
    refresh: 'تحديث قائمة النماذج',
    refreshing: 'جارٍ التحديث…',
    noModels: 'لم يُرجع المزوّد أي نماذج',
    noMatches: 'لا يوجد نموذج مطابق',
    cliInstalled: 'مثبّت',
    cliMissing: 'لم يتم العثور على {name}. ثبّته وتأكد من أنه يعمل في الطرفية.',
    cliNote: 'يستخدم {name} المثبّت والمسجّل دخوله لديك. لا حاجة إلى مفتاح API.',
    switchModel: 'تبديل نموذج الذكاء الاصطناعي',
    cliDefaultModel: 'النموذج الافتراضي لواجهة الأوامر',
    moreModels: 'إعدادات نموذج الذكاء الاصطناعي…',
    presets: 'الإعدادات المسبقة',
    savePreset: 'حفظ كإعداد مسبق',
    presetName: 'اسم الإعداد المسبق',
    deletePreset: 'حذف الإعداد المسبق',
    errApiKey: 'أدخل مفتاح API',
    errModel: 'أدخل معرّف النموذج',
    errBaseUrl: 'يحتاج المزوّد المخصّص إلى عنوان URL أساسي',
  },
  pt: {
    title: 'Modelo de IA',
    provider: 'Provedor',
    model: 'Modelo',
    modelHint: 'Escolha na lista ou digite qualquer id de modelo aceito pelo provedor.',
    apiKey: 'Chave de API',
    apiKeyKeep: 'Há uma chave salva. Deixe em branco para mantê-la.',
    removeKey: 'Remover chave',
    baseUrl: 'URL base',
    baseUrlHint: 'Endpoint compatível com OpenAI, por exemplo https://example.com/v1',
    gensparkHosted:
      'As chamadas ao modelo passam pelo Genspark. Nenhuma chave é guardada neste dispositivo.',
    signIn: 'Entrar no Genspark',
    signedInAs: 'Conectado como {email}',
    notSignedIn: 'Não conectado',
    storageNote:
      'As chaves ficam neste dispositivo, cifradas pelo chaveiro do sistema quando disponível, e só são enviadas ao provedor escolhido.',
    save: 'Salvar',
    cancel: 'Cancelar',
    test: 'Testar',
    testing: 'Testando…',
    testOk: 'A chave funciona',
    refresh: 'Atualizar lista de modelos',
    refreshing: 'Atualizando…',
    noModels: 'O provedor não retornou nenhum modelo',
    noMatches: 'Nenhum modelo correspondente',
    cliInstalled: 'Instalado',
    cliMissing: '{name} não foi encontrado. Instale-o e verifique se funciona num terminal.',
    cliNote: 'Usa o {name} que você já tem instalado e conectado. Não precisa de chave de API.',
    switchModel: 'Trocar de modelo de IA',
    cliDefaultModel: 'Modelo padrão da CLI',
    moreModels: 'Configurações do modelo de IA…',
    presets: 'Predefinições',
    savePreset: 'Salvar como predefinição',
    presetName: 'Nome da predefinição',
    deletePreset: 'Excluir predefinição',
    errApiKey: 'Informe uma chave de API',
    errModel: 'Informe um id de modelo',
    errBaseUrl: 'Um provedor personalizado precisa de uma URL base',
  },
  it: {
    title: 'Modello IA',
    provider: 'Provider',
    model: 'Modello',
    modelHint: "Scegli dall'elenco o digita un qualsiasi id di modello accettato dal provider.",
    apiKey: 'Chiave API',
    apiKeyKeep: 'Una chiave è salvata. Lascia vuoto per mantenerla.',
    removeKey: 'Rimuovi chiave',
    baseUrl: 'URL base',
    baseUrlHint: 'Endpoint compatibile con OpenAI, ad esempio https://example.com/v1',
    gensparkHosted:
      'Le chiamate al modello passano da Genspark. Nessuna chiave viene salvata su questo dispositivo.',
    signIn: 'Accedi a Genspark',
    signedInAs: 'Connesso come {email}',
    notSignedIn: 'Non connesso',
    storageNote:
      'Le chiavi restano su questo dispositivo, cifrate con il portachiavi di sistema quando disponibile, e vengono inviate solo al provider scelto.',
    save: 'Salva',
    cancel: 'Annulla',
    test: 'Prova',
    testing: 'Prova in corso…',
    testOk: 'La chiave funziona',
    refresh: 'Aggiorna elenco modelli',
    refreshing: 'Aggiornamento…',
    noModels: 'Il provider non ha restituito alcun modello',
    noMatches: 'Nessun modello corrispondente',
    cliInstalled: 'Installato',
    cliMissing: '{name} non è stato trovato. Installalo e verifica che funzioni nel terminale.',
    cliNote:
      'Usa il {name} già installato e con accesso effettuato. Nessuna chiave API necessaria.',
    switchModel: 'Cambia modello IA',
    cliDefaultModel: 'Modello predefinito della CLI',
    moreModels: 'Impostazioni del modello IA…',
    presets: 'Preimpostazioni',
    savePreset: 'Salva come preimpostazione',
    presetName: 'Nome della preimpostazione',
    deletePreset: 'Elimina preimpostazione',
    errApiKey: 'Inserisci una chiave API',
    errModel: 'Inserisci un id di modello',
    errBaseUrl: 'Un provider personalizzato richiede un URL base',
  },
  pl: {
    title: 'Model AI',
    provider: 'Dostawca',
    model: 'Model',
    modelHint:
      'Wybierz z listy albo wpisz dowolny identyfikator modelu akceptowany przez dostawcę.',
    apiKey: 'Klucz API',
    apiKeyKeep: 'Klucz jest zapisany. Zostaw puste, aby go zachować.',
    removeKey: 'Usuń klucz',
    baseUrl: 'Bazowy adres URL',
    baseUrlHint: 'Punkt końcowy zgodny z OpenAI, na przykład https://example.com/v1',
    gensparkHosted:
      'Wywołania modelu idą przez Genspark. Na tym urządzeniu nie jest przechowywany żaden klucz.',
    signIn: 'Zaloguj się do Genspark',
    signedInAs: 'Zalogowano jako {email}',
    notSignedIn: 'Niezalogowano',
    storageNote:
      'Klucze są przechowywane na tym urządzeniu, szyfrowane pękiem kluczy systemu, gdy jest dostępny, i wysyłane wyłącznie do wybranego dostawcy.',
    save: 'Zapisz',
    cancel: 'Anuluj',
    test: 'Testuj',
    testing: 'Testowanie…',
    testOk: 'Klucz działa',
    refresh: 'Odśwież listę modeli',
    refreshing: 'Odświeżanie…',
    noModels: 'Dostawca nie zwrócił żadnych modeli',
    noMatches: 'Brak pasującego modelu',
    cliInstalled: 'Zainstalowano',
    cliMissing: 'Nie znaleziono {name}. Zainstaluj go i sprawdź, czy działa w terminalu.',
    cliNote: 'Korzysta z zainstalowanego i zalogowanego {name}. Klucz API nie jest potrzebny.',
    switchModel: 'Zmień model AI',
    cliDefaultModel: 'Domyślny model CLI',
    moreModels: 'Ustawienia modelu AI…',
    presets: 'Ustawienia własne',
    savePreset: 'Zapisz jako ustawienie',
    presetName: 'Nazwa ustawienia',
    deletePreset: 'Usuń ustawienie',
    errApiKey: 'Podaj klucz API',
    errModel: 'Podaj identyfikator modelu',
    errBaseUrl: 'Własny dostawca wymaga bazowego adresu URL',
  },
  nl: {
    title: 'AI-model',
    provider: 'Aanbieder',
    model: 'Model',
    modelHint: 'Kies er een uit de lijst of typ een model-id die de aanbieder accepteert.',
    apiKey: 'API-sleutel',
    apiKeyKeep: 'Er is een sleutel opgeslagen. Laat leeg om die te behouden.',
    removeKey: 'Sleutel verwijderen',
    baseUrl: 'Basis-URL',
    baseUrlHint: 'OpenAI-compatibel eindpunt, bijvoorbeeld https://example.com/v1',
    gensparkHosted:
      'Modelaanroepen lopen via Genspark. Er wordt geen sleutel op dit apparaat bewaard.',
    signIn: 'Aanmelden bij Genspark',
    signedInAs: 'Aangemeld als {email}',
    notSignedIn: 'Niet aangemeld',
    storageNote:
      'Sleutels blijven op dit apparaat, versleuteld met de systeemsleutelhanger waar beschikbaar, en gaan alleen naar de aanbieder die je kiest.',
    save: 'Opslaan',
    cancel: 'Annuleren',
    test: 'Testen',
    testing: 'Bezig met testen…',
    testOk: 'Sleutel werkt',
    refresh: 'Modellijst vernieuwen',
    refreshing: 'Bezig met vernieuwen…',
    noModels: 'De aanbieder gaf geen modellen terug',
    noMatches: 'Geen overeenkomend model',
    cliInstalled: 'Geïnstalleerd',
    cliMissing:
      '{name} is niet gevonden. Installeer het en controleer of het in een terminal werkt.',
    cliNote:
      'Gebruikt de {name} die je al hebt geïnstalleerd en waarop je bent aangemeld. Geen API-sleutel nodig.',
    switchModel: 'AI-model wisselen',
    cliDefaultModel: 'Standaardmodel van de CLI',
    moreModels: 'AI-modelinstellingen…',
    presets: 'Voorinstellingen',
    savePreset: 'Opslaan als voorinstelling',
    presetName: 'Naam voorinstelling',
    deletePreset: 'Voorinstelling verwijderen',
    errApiKey: 'Voer een API-sleutel in',
    errModel: 'Voer een model-id in',
    errBaseUrl: 'Een eigen aanbieder heeft een basis-URL nodig',
  },
  ms: {
    title: 'Model AI',
    provider: 'Penyedia',
    model: 'Model',
    modelHint: 'Pilih daripada senarai, atau taip mana-mana id model yang diterima penyedia.',
    apiKey: 'Kunci API',
    apiKeyKeep: 'Kunci telah disimpan. Biarkan kosong untuk mengekalkannya.',
    removeKey: 'Buang kunci',
    baseUrl: 'Base URL',
    baseUrlHint: 'Titik akhir serasi OpenAI, contohnya https://example.com/v1',
    gensparkHosted:
      'Panggilan model disalurkan melalui Genspark. Tiada kunci disimpan pada peranti ini.',
    signIn: 'Log masuk ke Genspark',
    signedInAs: 'Log masuk sebagai {email}',
    notSignedIn: 'Belum log masuk',
    storageNote:
      'Kunci disimpan pada peranti ini, disulitkan dengan keychain sistem jika ada, dan hanya dihantar kepada penyedia yang anda pilih.',
    save: 'Simpan',
    cancel: 'Batal',
    test: 'Uji',
    testing: 'Sedang menguji…',
    testOk: 'Kunci berfungsi',
    refresh: 'Segar semula senarai model',
    refreshing: 'Sedang menyegarkan…',
    noModels: 'Penyedia tidak memulangkan sebarang model',
    noMatches: 'Tiada model yang sepadan',
    cliInstalled: 'Dipasang',
    cliMissing: '{name} tidak ditemui. Pasang dan pastikan ia boleh dijalankan dalam terminal.',
    cliNote: 'Menggunakan {name} yang sudah dipasang dan dilog masuk. Tiada kunci API diperlukan.',
    switchModel: 'Tukar model AI',
    cliDefaultModel: 'Model lalai CLI',
    moreModels: 'Tetapan model AI…',
    presets: 'Praset',
    savePreset: 'Simpan sebagai praset',
    presetName: 'Nama praset',
    deletePreset: 'Padam praset',
    errApiKey: 'Masukkan kunci API',
    errModel: 'Masukkan id model',
    errBaseUrl: 'Penyedia tersuai memerlukan base URL',
  },
  he: {
    title: 'מודל AI',
    provider: 'ספק',
    model: 'מודל',
    modelHint: 'בחר מהרשימה או הקלד כל מזהה מודל שהספק תומך בו.',
    apiKey: 'מפתח API',
    apiKeyKeep: 'קיים מפתח שמור. השאר ריק כדי לשמור עליו.',
    removeKey: 'מחיקת מפתח',
    baseUrl: 'כתובת בסיס',
    baseUrlHint: 'נקודת קצה תואמת OpenAI, לדוגמה https://example.com/v1',
    gensparkHosted: 'קריאות למודל עוברות דרך Genspark. לא נשמר מפתח במכשיר הזה.',
    signIn: 'התחברות ל-Genspark',
    signedInAs: 'מחובר כ-{email}',
    notSignedIn: 'לא מחובר',
    storageNote:
      'המפתחות נשמרים במכשיר הזה, מוצפנים במחזיק המפתחות של המערכת כשהוא זמין, ונשלחים רק לספק שבחרת.',
    save: 'שמירה',
    cancel: 'ביטול',
    test: 'בדיקה',
    testing: 'בודק…',
    testOk: 'המפתח פועל',
    refresh: 'רענון רשימת המודלים',
    refreshing: 'מרענן…',
    noModels: 'הספק לא החזיר מודלים',
    noMatches: 'אין מודל תואם',
    cliInstalled: 'מותקן',
    cliMissing: '{name} לא נמצא. התקן אותו וודא שהוא פועל בטרמינל.',
    cliNote: 'משתמש ב-{name} שכבר מותקן ומחובר אצלך. אין צורך במפתח API.',
    switchModel: 'החלפת מודל AI',
    cliDefaultModel: 'מודל ברירת המחדל של ה-CLI',
    moreModels: 'הגדרות מודל AI…',
    presets: 'הגדרות שמורות',
    savePreset: 'שמירה כהגדרה',
    presetName: 'שם ההגדרה',
    deletePreset: 'מחיקת ההגדרה',
    errApiKey: 'הזן מפתח API',
    errModel: 'הזן מזהה מודל',
    errBaseUrl: 'ספק מותאם דורש כתובת בסיס',
  },
  hi: {
    title: 'AI मॉडल',
    provider: 'प्रदाता',
    model: 'मॉडल',
    modelHint: 'सूची से चुनें, या प्रदाता द्वारा स्वीकृत कोई भी मॉडल आईडी लिखें।',
    apiKey: 'API कुंजी',
    apiKeyKeep: 'एक कुंजी सहेजी गई है। इसे बनाए रखने के लिए खाली छोड़ें।',
    removeKey: 'कुंजी हटाएँ',
    baseUrl: 'बेस URL',
    baseUrlHint: 'OpenAI-संगत एंडपॉइंट, उदाहरण के लिए https://example.com/v1',
    gensparkHosted: 'मॉडल कॉल Genspark के ज़रिए जाती हैं। इस डिवाइस पर कोई कुंजी नहीं रखी जाती।',
    signIn: 'Genspark में साइन इन करें',
    signedInAs: '{email} के रूप में साइन इन',
    notSignedIn: 'साइन इन नहीं',
    storageNote:
      'कुंजियाँ इसी डिवाइस पर रहती हैं, सिस्टम कीचेन उपलब्ध होने पर एन्क्रिप्टेड, और केवल आपके चुने हुए प्रदाता को भेजी जाती हैं।',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    test: 'परीक्षण',
    testing: 'परीक्षण हो रहा है…',
    testOk: 'कुंजी काम करती है',
    refresh: 'मॉडल सूची ताज़ा करें',
    refreshing: 'ताज़ा हो रहा है…',
    noModels: 'प्रदाता ने कोई मॉडल नहीं लौटाया',
    noMatches: 'कोई मेल खाता मॉडल नहीं',
    cliInstalled: 'इंस्टॉल है',
    cliMissing: '{name} नहीं मिला। इसे इंस्टॉल करें और सुनिश्चित करें कि यह टर्मिनल में चलता है।',
    cliNote: 'आपके पहले से इंस्टॉल और साइन-इन {name} का उपयोग करता है। API कुंजी की ज़रूरत नहीं।',
    switchModel: 'AI मॉडल बदलें',
    cliDefaultModel: 'CLI का डिफ़ॉल्ट मॉडल',
    moreModels: 'AI मॉडल सेटिंग…',
    presets: 'प्रीसेट',
    savePreset: 'प्रीसेट के रूप में सहेजें',
    presetName: 'प्रीसेट का नाम',
    deletePreset: 'प्रीसेट हटाएँ',
    errApiKey: 'API कुंजी दर्ज करें',
    errModel: 'मॉडल आईडी दर्ज करें',
    errBaseUrl: 'कस्टम प्रदाता के लिए बेस URL आवश्यक है',
  },
  'zh-TW': {
    title: 'AI 模型',
    provider: '提供者',
    model: '模型',
    modelHint: '可從清單挑選，也可直接填寫提供者支援的任何模型 ID。',
    apiKey: 'API Key',
    apiKeyKeep: '已儲存金鑰；留空即維持不變。',
    removeKey: '刪除金鑰',
    baseUrl: 'Base URL',
    baseUrlHint: '相容 OpenAI 的端點位址，例如 https://example.com/v1',
    gensparkHosted: '模型呼叫經由 Genspark 轉送，本機不會保存金鑰。',
    signIn: '登入 Genspark',
    signedInAs: '已登入：{email}',
    notSignedIn: '尚未登入',
    storageNote: '金鑰僅保存在本機，系統提供鑰匙圈時會加密儲存，且只會隨請求送往你所選擇的提供者。',
    save: '儲存',
    cancel: '取消',
    test: '測試',
    testing: '測試中…',
    testOk: '金鑰可用',
    refresh: '重新整理模型清單',
    refreshing: '重新整理中…',
    noModels: '該提供者未回傳任何模型',
    noMatches: '沒有符合的模型',
    cliInstalled: '已安裝',
    cliMissing: '找不到 {name}。請先安裝並確認可在終端機執行。',
    cliNote: '改用本機已安裝並登入的 {name}，不需要 API Key。',
    switchModel: '切換 AI 模型',
    cliDefaultModel: 'CLI 預設模型',
    moreModels: 'AI 模型設定…',
    presets: '預設組合',
    savePreset: '存為預設組合',
    presetName: '預設組合名稱',
    deletePreset: '刪除預設組合',
    errApiKey: '請填寫 API Key',
    errModel: '請填寫模型 ID',
    errBaseUrl: '自訂提供者需要填寫 Base URL',
  },
})

export const tAiSettings = createI18n(aiSettingsStrings)
